<?php

/**
 * Banks name and code for PHP - small and easy-to-use library for getting Czech code or name of bank 
 *
 * @author     Ondřej Kubíček
 * @copyright  Copyright (c) 2014 Ondřej Kubíček
 * @license    New BSD License
 * @link       http://bank.kubon.cz
 * @version    1.0
 */
class Bank
{

	private static $banks = array(
		  '0100' => 'Komerční banka',
		  '0300' => 'Československá obchodní banka | Poštovní spořitelna', //there are two banks with the same code
		  '0600' => 'GE Money Bank',
		  '0710' => 'Česká národní banka',
		  '0800' => 'Česká spořitelna',
		  '2010' => 'Fio banka',
		  '2020' => 'Bank of Tokyo-Mitsubishi',
		  '2100' => 'Hypoteční banka',
		  '2210' => 'Evropsko-ruská banka',
		  '2230' => 'AXA Bank',
		  '2240' => 'Poštová banka, a.s.',
		  '2310' => 'Zuno',
		  '2600' => 'Citibank',
		  '2700' => 'UniCredit Bank',
		  '3030' => 'Air Bank',
		  '3500' => 'ING Bank N.V.',
		  '4000' => 'LBBW Bank CZ',
		  '4300' => 'Českomoravská záruční a rozvojová banka',
		  '5000' => 'Crédit Agricole',
		  '5400' => 'Royal Bank of Scotland',
		  '5500' => 'Raiffeisenbank',
		  '5800' => 'J&T BANKA',
		  '6000' => 'PPF banka',
		  '6100' => 'Equa bank',
		  '6200' => 'COMMERZBANK Aktiengesellschaft',
		  '6210' => 'mBank',
		  '6300' => 'Fortis Bank SA/NV',
		  '6700' => 'Všeobecná úverová banka',
		  '6800' => 'Sberbank CZ',
		  '7910' => 'Deutsche Bank',
		  '7940' => 'Waldviertler Sparkasse von 1842 AG',
		  '7950' => 'Raiffeisen stavební spořitelna',
		  '7960' => 'Českomoravská stavební spořitelna',
		  '7970' => 'Wüstenrot - stavební spořitelna',
		  '7980' => 'Wüstenrot hypoteční banka',
		  '7990' => 'Modrá pyramida stavební spořitelna',
		  '8030' => 'Raiffeisenbank im Stiftland eG',
		  '8040' => 'Oberbank AG',
		  '8060' => 'Stavební spořitelna České spořitelny',
		  '8070' => 'HYPO stavební spořitelna',
		  '8090' => 'Česká exportní banka',
		  '8150' => 'HSBC Bank plc - pobočka Praha',
		  '8200' => 'PRIVAT BANK AG',
		  '8211' => 'Saxo Bank A/S',
		  '8221' => 'Volksbank Löbau-Zittau eG',
		  '8231' => 'Bank Gutmann Aktiengesellschaft'
	);

	/**
	 * @param int code
	 * @return string
	 * @throws BankException
	 */
	public static function getName($code)
	{
		if (is_numeric($code) && array_key_exists($code, self::$banks)) {
			return self::$banks[$code];
		}
		throw new BankException('Bad code');
	}

	/**
	 * @param string 
	 * @return array
	 * @throws BankException
	 */
	public static function getCodes($name)
	{
		$ret = array_filter(self::$banks, function($var) use ($name) { return strpos(strtolower($var), strtolower($name)) !== false; });
		if (!empty($ret)) {
			return $ret;
		}
		throw new BankException('No match found');
	}
}

/**
 * An exception generated by Bank.
 */
class BankException extends Exception
{
}